### PR TITLE
add support for specifying a private key and header fields

### PR DESCRIPTION
**Pull request by koenpunt**
I guess the title says it all.

Both are necessary for when you want to generate JWTs for the [Apple App Store Connect API](https://developer.apple.com/documentation/appstoreconnectapi/generating_tokens_for_api_requests).

Passing in a file path for a private key will have precedence over the "Secret" option.

### CODE REVIEW

**Comment by mjamado** [comment]
Seems fine to me. Will update and publish right away.

**Comment by mjamado** [comment]
Actually... As it already happened before, this change will break current instalations, because the order of the parameters changed. Sorry for that (again).

**Comment by mjamado** [comment]
Ok, changed a few things around to avoid breaking previous working installations. Also, some lint and test fixes.

Please run lint and tests before making pull requests.

**Comment by koenpunt** [comment]
> Please run lint and tests before making pull requests.

I'm sorry, didn't realise there were any I guess. Have you considered setting up CI for running lint and test?

**Comment by mjamado** [comment]
I've considered it (most of my projects have it), but I'm lazy that way. ¯\_(ツ)_/¯

It's done now. This project doesn't change all that often to make the effort worthy.

**Pull request merged**
