### PR TITLE
Add option to change algorithm.

### PR DESCRIPTION
**Pull request by aljacinto**
Great job on the plugin, works perfectly except some of the services I'm calling are using different algorithms.  Added that feature in this PR.  I didn't see a contribution guideline, hope everything is good.  Let me know if you want me to change something.

image

Thanks.

### CODE REVIEW

**Review by akos-gg — APPROVED** [review]

**Comment by pgp** [comment]
Hi, I'm trying to use this plugin to encode a RS256 key from Insomnia on Linux, and in the `Secret` field I'm providing (by copy/paste) the content of a RSA private key file encoded in PEM format, generated by:
`openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:4096`

The error appearing in the `Live preview` box is:
`error:0906D06C:PEM routines:PEM_read_bio:no start line`

In which encoding am I supposed to provide the private key?

**Comment by mjamado** [comment]
@pgp The plugin didn't support RS256 keys up until now. Just now have I merged this PR.

@aljacinto and @pootyx, I'm so sorry for the delay. I've just merged this PR blindly, just because so many time has passed already. Please don't break, please don't break, please don't break.

**Comment by pgp** [comment]
Yes, infact I was asking @aljacinto , I wrote here because it seemed a good context. The doubt I have is, maybe the text field for secret does not support newlines, so it breaks format when pasting...

**Comment by AlJac-bit** [comment]
ahh did not test that case, sorry about that.  I was trying to do it through environment variable but can't get it to work.

**Comment by pgp** [comment]
Ok, I just checked, I confirm that PEM private key works if taken as environment variable (that is, putting the content of the PEM file in the environment as a JSON value - i.e. JSON-escaped). That suffices for my needs, thanks.

**Pull request merged**
